create or replace PROCEDURE SEND_PENDING_ORDERS
IS
    V_EMAIL VARCHAR2(200);
    V_NAME  VARCHAR2(200);
    V_MSG   CLOB;

    CURSOR C1 IS
        SELECT DISTINCT EMP_CODE
        FROM SALES_ORDER
        WHERE ORDER_STATUS = 'F'
        AND
         TRUNC(ORDER_DATE) <= TRUNC(SYSDATE) - 1  
        ;

    CURSOR C2(P_EMP_CODE NUMBER) IS
        SELECT ORDER_ID,
               ORDER_DATE,
               CUSTOMER_NAME,
               CUSTOMER_MOBILE,
               TOTAL_AMOUNT
        FROM SALES_ORDER
        WHERE EMP_CODE = P_EMP_CODE
          AND ORDER_STATUS = 'F'
          AND TRUNC(ORDER_DATE) <= TRUNC(SYSDATE) - 1  
        ORDER BY ORDER_DATE;

BEGIN

    FOR I IN C1 LOOP

     DBMS_OUTPUT.PUT_LINE('EMP_CODE = ' || I.EMP_CODE);
       BEGIN
           SELECT EMP_NAME_EN,
                   EMAIL
            INTO V_NAME,
                 V_EMAIL
            FROM ORG_EMPLOYEE
            WHERE EMP_CODE = I.EMP_CODE;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                CONTINUE;
        END;

      IF V_EMAIL IS NULL THEN
          CONTINUE;
      END IF;

      V_MSG :=
'<html><body style="font-family:Arial,sans-serif;">'||
'<h2>Pending Sales Orders</h2>'||
'<p>Dear '||V_NAME||',</p>'||
'<p>Please find below the list of pending sales orders assigned to you.</p>'||

'<table border="1" cellpadding="5" cellspacing="0" style="border-collapse:collapse;">'||
'<tr style="background:#dddddd;">'||
'<th>Order ID</th>'||
'<th>Order Date</th>'||
'<th>Customer Name</th>'||
'<th>Mobile</th>'||
'<th>Total Amount</th>'||
'</tr>';

FOR R IN C2(I.EMP_CODE) LOOP

    V_MSG := V_MSG ||
    '<tr>'||
    '<td>'||R.ORDER_ID||'</td>'||
    '<td>'||TO_CHAR(R.ORDER_DATE,'DD/MM/YYYY')||'</td>'||
    '<td>'||R.CUSTOMER_NAME||'</td>'||
    '<td>'||R.CUSTOMER_MOBILE||'</td>'||
    '<td align="right">'||TO_CHAR(R.TOTAL_AMOUNT,'999G999G990D00')||'</td>'||
    '</tr>';

END LOOP;

V_MSG := V_MSG ||
'</table>'||
'<br>'||
'<p>Please review these orders and take the necessary action.</p>'||
'<br>'||
'<p>Regards,<br>Sales System</p>'||
'<hr>'||
'<small>This is an automated email generated by the system.</small>'||
'</body></html>';

DECLARE
    L_MAIL_ID NUMBER;
    L_BODY     CLOB;
    L_BODY_HTML CLOB;
BEGIN
    L_BODY      := 'Your email client does not support HTML.';
    L_BODY_HTML := V_MSG;

    L_MAIL_ID := APEX_MAIL.SEND(
        p_to        => V_EMAIL,
        p_from      => 'Test@tgmail.com',
        p_subj      => 'Pending Sales Orders',
        p_body      => L_BODY,
        p_body_html => L_BODY_HTML
    );
END;

END LOOP;

COMMIT;

APEX_MAIL.PUSH_QUEUE;

END;
/